import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';
import { GoogleGenAI } from '@google/genai';
const execAsync = promisify(exec);

const OUTPUTS_DIR = path.join(process.cwd(), 'outputs', 'audio');
fs.mkdirSync(OUTPUTS_DIR, { recursive: true });
function cleanText(text: string) { return String(text || '').replace(/\s+/g, ' ').trim(); }
async function probeDuration(filePath: string) { const { stdout } = await execAsync(`ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "${filePath}"`); const d=Number.parseFloat(stdout.trim()); if(!Number.isFinite(d)||d<=0) throw new Error('Unable to determine audio duration'); return d; }

export type TTSProviderName = 'auto'|'gemini'|'google'|'vieneu'|'capcut'|'elevenlabs';
export type TTSOptions = { provider?:TTSProviderName; voiceId?:string; modelId?:string; lang?:string; stability?:number; similarityBoost?:number; rate?:number; };
export type TTSResult = {success:true;url:string;filePath:string;duration:number;provider:string;voiceId?:string;modelId?:string};

const GEMINI_VOICES: Record<string,string> = {
  vi_female:'Kore', vi_male:'Charon', en_male:'Puck', en_female:'Aoede',
  Kore:'Kore', Puck:'Puck', Charon:'Charon', Aoede:'Aoede', Fenrir:'Fenrir', Leda:'Leda', Orus:'Orus', Zephyr:'Zephyr'
};
function resolveGeminiVoice(id?:string) { return GEMINI_VOICES[id || ''] || process.env.GEMINI_TTS_VOICE || 'Kore'; }
function detectLang(text:string, opts:TTSOptions) { if(opts.lang) return opts.lang; if(opts.voiceId?.startsWith('en_')) return 'en-US'; return /[àáảãạăằắẳẵặâầấẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡùúủũụưừứửữựỳýỷỹỵđ]/i.test(text)?'vi-VN':'en-US'; }

function pcmToWav(pcm:Buffer, sampleRate=24000, channels=1, bits=16) { const blockAlign=channels*bits/8; const byteRate=sampleRate*blockAlign; const out=Buffer.alloc(44+pcm.length); out.write('RIFF',0); out.writeUInt32LE(36+pcm.length,4); out.write('WAVE',8); out.write('fmt ',12); out.writeUInt32LE(16,16); out.writeUInt16LE(1,20); out.writeUInt16LE(channels,22); out.writeUInt32LE(sampleRate,24); out.writeUInt32LE(byteRate,28); out.writeUInt16LE(blockAlign,32); out.writeUInt16LE(bits,34); out.write('data',36); out.writeUInt32LE(pcm.length,40); pcm.copy(out,44); return out; }

async function cleanAndNormalizeAudio(inputPath:string, outputPath:string) {
  // Conservative broadcast cleanup: remove DC/rumble, tame hiss, normalize loudness without aggressive compression.
  await execAsync(`ffmpeg -y -i "${inputPath}" -af "highpass=f=70,lowpass=f=12000,afftdn=nf=-28,loudnorm=I=-16:TP=-1.5:LRA=7" -ar 48000 -ac 1 -c:a pcm_s16le "${outputPath}"`);
}

export async function generateGeminiTTS(text:string, opts:TTSOptions={}):Promise<TTSResult>{
  const key=process.env.GEMINI_API_KEY; if(!key) throw new Error('GEMINI_API_KEY is not configured');
  const clean=cleanText(text); if(!clean) throw new Error('TTS input text cannot be empty');
  const modelId=opts.modelId||process.env.GEMINI_TTS_MODEL||'gemini-3.1-flash-tts-preview';
  const voice=resolveGeminiVoice(opts.voiceId);
  const lang=detectLang(clean,opts);
  const ai=new GoogleGenAI({apiKey:key});
  const prompt=`Speak the following documentary narration in a calm, precise, restrained broadcast voice. Natural pauses, clear Vietnamese/English pronunciation, no music, no sound effects, no room ambience, no whispering. Language: ${lang}. Text: ${clean}`;
  const interaction=await (ai as any).interactions.create({model:modelId,input:prompt,response_format:{type:'audio'},generation_config:{speech_config:[{voice,language:lang}]}});
  const data=interaction?.output_audio?.data;
  if(!data) throw new Error('Gemini TTS returned no audio data');
  const id=`voice_gemini_${Date.now()}`; const temp=path.join(OUTPUTS_DIR,`${id}_raw.wav`); const final=path.join(OUTPUTS_DIR,`${id}.wav`);
  fs.writeFileSync(temp,pcmToWav(Buffer.from(data,'base64')));
  try { await cleanAndNormalizeAudio(temp,final); } finally { if(fs.existsSync(temp))fs.unlinkSync(temp); }
  return {success:true,url:`/outputs/audio/${id}.wav`,filePath:final,duration:await probeDuration(final),provider:'gemini',voiceId:voice,modelId};
}

async function downloadGoogleTTSChunk(text:string,lang:string,out:string){const url=`https://translate.google.com/translate_tts?ie=UTF-8&q=${encodeURIComponent(text)}&tl=${lang}&client=tw-ob`;const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0','Accept':'audio/mpeg, audio/*; q=0.9, */*; q=0.5'}});if(!r.ok)throw new Error(`Google TTS request failed (${r.status})`);fs.writeFileSync(out,Buffer.from(await r.arrayBuffer()));}
export async function generateGoogleTTS(text:string,opts:TTSOptions={}):Promise<TTSResult>{const clean=cleanText(text);if(!clean)throw new Error('TTS input text cannot be empty');const vi=opts.lang==='vi'||opts.voiceId?.startsWith('vi')||detectLang(clean,opts)==='vi-VN';const lang=vi?'vi':'en';const sentences=clean.split(/(?<=[.!?,;:])\s+/);const chunks:string[]=[];let cur='';for(const s of sentences){if((cur+' '+s).trim().length>130&&cur){chunks.push(cur.trim());cur=s;}else cur=cur?`${cur} ${s}`:s;}if(cur)chunks.push(cur.trim());const id=`voice_google_${Date.now()}`;const tempDir=path.join(process.cwd(),'temp_renders',id);fs.mkdirSync(tempDir,{recursive:true});const files:string[]=[];for(let i=0;i<chunks.length;i++){const f=path.join(tempDir,`chunk_${String(i).padStart(3,'0')}.mp3`);await downloadGoogleTTSChunk(chunks[i],lang,f);files.push(f);}const list=path.join(tempDir,'chunks.txt');fs.writeFileSync(list,files.map(f=>`file '${f.replace(/'/g,"'\\''")}'`).join('\n'));const raw=path.join(tempDir,'concat.mp3');await execAsync(`ffmpeg -y -f concat -safe 0 -i "${list}" -c copy "${raw}"`);const final=path.join(OUTPUTS_DIR,`${id}.wav`);await cleanAndNormalizeAudio(raw,final);fs.rmSync(tempDir,{recursive:true,force:true});return{success:true,url:`/outputs/audio/${id}.wav`,filePath:final,duration:await probeDuration(final),provider:'google',voiceId:opts.voiceId||(vi?'vi_female':'en_male'),modelId:lang};}

async function saveRemoteAudio(url:string,provider:string,ext='mp3'){const r=await fetch(url);if(!r.ok)throw new Error(`${provider} audio download failed (${r.status})`);const id=`voice_${provider}_${Date.now()}`;const raw=path.join(OUTPUTS_DIR,`${id}.${ext}`);fs.writeFileSync(raw,Buffer.from(await r.arrayBuffer()));const final=path.join(OUTPUTS_DIR,`${id}.wav`);await cleanAndNormalizeAudio(raw,final);if(fs.existsSync(raw))fs.unlinkSync(raw);return{success:true as const,url:`/outputs/audio/${id}.wav`,filePath:final,duration:await probeDuration(final)};}
async function isVieNeuAvailable(){const base=(process.env.VIENU_TTS_URL||'http://127.0.0.1:8000').replace(/\/$/,'');try{const r=await fetch(`${base}/v1/models`,{signal:AbortSignal.timeout(1200)});return r.ok;}catch{return false;}}
async function generateVieNeu(text:string,opts:TTSOptions):Promise<TTSResult>{const base=(process.env.VIENU_TTS_URL||'http://127.0.0.1:8000').replace(/\/$/,'');const voice=opts.voiceId||process.env.VIENU_TTS_VOICE||'Mai Anh';const modelId=opts.modelId||process.env.VIENU_TTS_MODEL||'vieneu-v3-turbo';const headers:Record<string,string>={'Content-Type':'application/json'};if(process.env.VIENU_TTS_API_KEY)headers.Authorization=`Bearer ${process.env.VIENU_TTS_API_KEY}`;const r=await fetch(`${base}/v1/audio/speech`,{method:'POST',headers,body:JSON.stringify({model:modelId,input:cleanText(text),voice,response_format:'wav',sample_rate:48000})});if(!r.ok)throw new Error(`VieNeu TTS failed (${r.status}): ${await r.text()}`);const id=`voice_vieneu_${Date.now()}`;const raw=path.join(OUTPUTS_DIR,`${id}.wav`);fs.writeFileSync(raw,Buffer.from(await r.arrayBuffer()));const final=path.join(OUTPUTS_DIR,`${id}_clean.wav`);await cleanAndNormalizeAudio(raw,final);fs.unlinkSync(raw);return{success:true,url:`/outputs/audio/${id}_clean.wav`,filePath:final,duration:await probeDuration(final),provider:'vieneu',voiceId:voice,modelId};}
async function generateCapCut(text:string,opts:TTSOptions):Promise<TTSResult>{const python=process.env.CAPCUT_PYTHON||'python';const script=path.join(process.cwd(),'server','tts','capcut_bridge.py');const voice=opts.voiceId||process.env.CAPCUT_TTS_VOICE||'BV074_streaming';const rate=String(opts.rate??Number(process.env.CAPCUT_TTS_RATE||'1.0'));const args=[python,script,'--text',JSON.stringify(cleanText(text)),'--voice',JSON.stringify(voice),'--rate',rate];const command=args.map(a=>`"${a.replace(/"/g,'\\"')}"`).join(' ');const{stdout,stderr}=await execAsync(command,{timeout:Number(process.env.CAPCUT_TTS_TIMEOUT_MS||120000),maxBuffer:1024*1024});if(stderr.trim())console.warn('[CapCut TTS]',stderr.trim());const line=stdout.trim().split(/\r?\n/).filter(Boolean).pop();if(!line)throw new Error('CapCut bridge returned no result');const result=JSON.parse(line);if(!result.speech_url)throw new Error(result.error||'CapCut response did not contain speech_url');const saved=await saveRemoteAudio(result.speech_url,'capcut','mp3');return{...saved,provider:'capcut',voiceId:result.voice||voice};}
async function generateElevenLabs(text:string,opts:TTSOptions):Promise<TTSResult>{const key=process.env.ELEVENLABS_API_KEY;if(!key)throw new Error('ELEVENLABS_API_KEY is not configured');const voiceId=opts.voiceId||process.env.ELEVENLABS_VOICE_ID;if(!voiceId)throw new Error('ELEVENLABS_VOICE_ID is not configured');const modelId=opts.modelId||process.env.ELEVENLABS_MODEL_ID||'eleven_multilingual_v2';const r=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(voiceId)}`,{method:'POST',headers:{'xi-api-key':key,'Content-Type':'application/json',Accept:'audio/mpeg'},body:JSON.stringify({text:cleanText(text),model_id:modelId,voice_settings:{stability:opts.stability??.55,similarity_boost:opts.similarityBoost??.8,style:.05,use_speaker_boost:true}})});if(!r.ok)throw new Error(`ElevenLabs TTS failed (${r.status})`);const saved=await saveRemoteAudio(`data:audio/mpeg;base64,${Buffer.from(await r.arrayBuffer()).toString('base64')}`,'elevenlabs','mp3');return{...saved,provider:'elevenlabs',voiceId,modelId};}
async function isGeminiAvailable(){return Boolean(process.env.GEMINI_API_KEY);}
async function isCapCutAvailable(){const python=process.env.CAPCUT_PYTHON||'python3';const script=path.join(process.cwd(),'server','tts','capcut_bridge.py');if(!fs.existsSync(script))return false;try{await execAsync(`"${python}" -c "import capcut_tts_api"`,{timeout:2000});return true;}catch{return false;}}
export async function getTTSProviders(){return{gemini:await isGeminiAvailable(),google:true,vieneu:await isVieNeuAvailable(),capcut:await isCapCutAvailable(),elevenlabs:Boolean(process.env.ELEVENLABS_API_KEY),voices:Object.keys(GEMINI_VOICES).filter(k=>k.includes('_'))};}

export async function generateVoice(text:string,opts:TTSOptions={}){const clean=cleanText(text);if(!clean)throw new Error('Voice text is empty');const requested=opts.provider||(process.env.TTS_PROVIDER as TTSProviderName)||'auto';if(requested==='gemini')return generateGeminiTTS(clean,opts);if(requested==='google')return generateGoogleTTS(clean,opts);if(requested==='vieneu'){if(await isVieNeuAvailable())return generateVieNeu(clean,opts);return generateGeminiTTS(clean,opts).catch(()=>generateGoogleTTS(clean,opts));}if(requested==='capcut'){if(await isCapCutAvailable())try{return await generateCapCut(clean,opts);}catch(e){console.warn('[TTS] CapCut failed',e);}return generateGeminiTTS(clean,opts).catch(()=>generateGoogleTTS(clean,opts));}if(requested==='elevenlabs'){if(process.env.ELEVENLABS_API_KEY)try{return await generateElevenLabs(clean,opts);}catch(e){console.warn('[TTS] ElevenLabs failed',e);}return generateGeminiTTS(clean,opts).catch(()=>generateGoogleTTS(clean,opts));}if(await isGeminiAvailable())try{return await generateGeminiTTS(clean,opts);}catch(e){console.warn('[TTS] Gemini failed, trying local/Google fallback',e);}if(await isVieNeuAvailable())try{return await generateVieNeu(clean,opts);}catch{}if(await isCapCutAvailable())try{return await generateCapCut(clean,opts);}catch{}if(process.env.ELEVENLABS_API_KEY)try{return await generateElevenLabs(clean,opts);}catch{}return generateGoogleTTS(clean,opts);}

export function buildBeatTimeline(shots:any[],totalDuration:number,minWords=5,maxWords=8){const safe=Array.isArray(shots)?shots:[];const all=safe.flatMap(s=>cleanText(s.narration).split(/\s+/).filter(Boolean));if(!all.length)return[];const beats:any[]=[];let globalWord=0,cursor=0;const spw=totalDuration/all.length;for(const shot of safe){const words=cleanText(shot.narration).split(/\s+/).filter(Boolean);if(!words.length)continue;const start=Number(shot.start)||cursor;const end=Number(shot.end)||start+words.length*spw;const target=Math.max(1,Math.round(words.length/6));const size=Math.max(minWords,Math.min(maxWords,Math.ceil(words.length/target)));for(let i=0;i<words.length;i+=size){const group=words.slice(i,Math.min(i+size,words.length));const a=start+(end-start)*(i/words.length),b=start+(end-start)*((i+group.length)/words.length);beats.push({id:`beat_${String(beats.length+1).padStart(3,'0')}`,shotId:shot.shot_id,start:Number(a.toFixed(3)),end:Number(b.toFixed(3)),duration:Number((b-a).toFixed(3)),text:group.join(' '),words:group,wordStart:globalWord+i,wordEnd:globalWord+i+group.length,visualCue:shot.visual_idea||shot.narration});}globalWord+=words.length;cursor=end;}return beats;}
export async function normalizeProjectToVoiceTimeline(project:any,voiceDuration:number){const shots=JSON.parse(JSON.stringify(project.shots||[]));const counts=shots.map((s:any)=>cleanText(s.narration).split(/\s+/).filter(Boolean).length);const total=counts.reduce((a:number,b:number)=>a+b,0)||1;let cursor=0;for(let i=0;i<shots.length;i++){const d=voiceDuration*(counts[i]/total);shots[i].start=Number(cursor.toFixed(3));shots[i].duration=Number(d.toFixed(3));shots[i].end=Number((cursor+d).toFixed(3));cursor+=d;}if(shots.length)shots[shots.length-1].end=Number(voiceDuration.toFixed(3));return{shots,beats:buildBeatTimeline(shots,voiceDuration)};}
