import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Sliders, Sparkles, Upload, Layers, Scissors, CheckCircle2, AlertCircle, Plus, Trash2, GripVertical, Info, Wand2 } from 'lucide-react';
import { Project, Shot, VisualAsset, MotionID, LayoutID, PhysicalBorderID } from '../types.ts';
import { VOX_LAYOUTS, VOX_MOTIONS } from '../presets/index.ts';
import { buildAssetPrompt, ensureCompositionAssets, getCompositionRecipe, getMotionHelp, validateComposition, inferBackground, inferMotion, describeAssetRole } from '../visualDirector/PhysicalCollage.ts';

interface AssetInspectorViewProps {
  project: Project;
  activeShotIndex: number;
  setActiveShotIndex: (idx: number) => void;
  onUpdateShot: (index: number, updated: Partial<Shot>) => void;
  onGenerateShotAsset?: (shotIndex: number, assetId: string) => void;
  onUploadShotAsset?: (shotIndex: number, assetId: string, file: File) => void;
  generatingAssetKey?: string | null;
}

const motionNames: Record<string,string> = Object.fromEntries(VOX_MOTIONS.map(m => [m.id, m.name]));

export const AssetInspectorView: React.FC<AssetInspectorViewProps> = ({ project, activeShotIndex, setActiveShotIndex, onUpdateShot, onGenerateShotAsset, onUploadShotAsset, generatingAssetKey }) => {
  const activeShot = project.shots[activeShotIndex] || project.shots[0];
  const [selectedAssetId, setSelectedAssetId] = useState<string | undefined>(activeShot?.assets?.[0]?.id);
  const [promptText, setPromptText] = useState('');
  const [negativePrompt, setNegativePrompt] = useState('cartoon, 3d render, glossy, modern UI, watermark, oversaturated, text artifacts');
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  const assets = activeShot?.assets || [];
  const selectedAsset = assets.find(a => a.id === selectedAssetId) || assets[0];
  const recipe = useMemo(() => activeShot ? getCompositionRecipe(activeShot.layout) : getCompositionRecipe('hero_archive'), [activeShot?.layout]);
  const compositionErrors = activeShot ? validateComposition(activeShot) : [];

  useEffect(() => {
    setSelectedAssetId(activeShot?.assets?.[0]?.id);
  }, [activeShot?.shot_id]);

  useEffect(() => {
    setPromptText(selectedAsset?.assetPrompt || '');
  }, [selectedAsset?.id]);

  const updateAssets = (next: VisualAsset[]) => onUpdateShot(activeShotIndex, { assets: next });

  const updateAsset = (id: string, patch: Partial<VisualAsset>) => {
    updateAssets(assets.map(a => a.id === id ? { ...a, ...patch } : a));
  };

  const prepareComposition = () => {
    if (!activeShot) return;
    const prepared = ensureCompositionAssets(activeShot);
    const background = inferBackground(prepared.layout);
    const composition = {
      layout: prepared.layout,
      background,
      border: (prepared.composition?.border || 'scissor_cut') as PhysicalBorderID,
      primaryMotion: prepared.assets[0]?.motion || inferMotion(prepared.layout),
      autoGenerated: true,
      assetCount: prepared.assets.length,
    };
    onUpdateShot(activeShotIndex, { assets: prepared.assets, background: { ...prepared.background, type: background }, composition });
    setSelectedAssetId(prepared.assets[0]?.id);
  };

  const addAsset = () => {
    if (!activeShot) return;
    if (assets.length >= recipe.maxAssets) return;
    const index = assets.length;
    const role = describeAssetRole(activeShot.layout, index);
    const id = `${activeShot.shot_id}_${role}_${index + 1}_${Date.now().toString(36)}`;
    const asset: VisualAsset = {
      id,
      type: 'image',
      role,
      source: '',
      assetPrompt: buildAssetPrompt(activeShot, role, index),
      provider: 'gemini',
      status: 'pending',
      position: { x: 50, y: 50 },
      scale: role === 'hero' ? .92 : .72,
      rotation: index % 2 ? -2.5 : 2.5,
      motion: inferMotion(activeShot.layout, index),
      start: .25 + index * .18,
      filter: 'high_contrast',
      paperCutout: true,
      shadow: { enabled: true, offset: [10,14], blur: 18, opacity: .42 },
    };
    updateAssets([...assets, asset]);
    setSelectedAssetId(id);
  };

  const removeAsset = (id: string) => {
    if (assets.length <= 1) return;
    const next = assets.filter(a => a.id !== id);
    updateAssets(next);
    if (selectedAssetId === id) setSelectedAssetId(next[0]?.id);
  };

  const handleLayoutChange = (newLayout: LayoutID) => {
    if (!activeShot) return;
    const seeded = ensureCompositionAssets({ ...activeShot, layout: newLayout });
    const bg = inferBackground(newLayout);
    onUpdateShot(activeShotIndex, {
      layout: newLayout,
      background: { ...activeShot.background, type: bg },
      assets: seeded.assets,
      composition: { layout:newLayout, background:bg, border:activeShot.composition?.border || 'scissor_cut', primaryMotion:inferMotion(newLayout), autoGenerated:true, assetCount:seeded.assets.length },
    });
  };

  const handleMotionChange = (motion: MotionID) => {
    if (!selectedAsset) return;
    updateAsset(selectedAsset.id, { motion });
    onUpdateShot(activeShotIndex, { composition: { ...(activeShot.composition || { layout:activeShot.layout, background:activeShot.background.type, border:'scissor_cut', primaryMotion:motion }), primaryMotion:motion } });
  };

  const generateOne = (asset: VisualAsset) => {
    if (!onGenerateShotAsset) return;
    if (!asset.assetPrompt) updateAsset(asset.id, { assetPrompt: buildAssetPrompt(activeShot, asset.role, assets.indexOf(asset)) });
    onGenerateShotAsset(activeShotIndex, asset.id);
  };

  const generateAll = async () => {
    if (!onGenerateShotAsset) return;
    for (const asset of assets.filter(a => a.type === 'image' && !a.source)) {
      generateOne(asset);
      await new Promise(resolve => setTimeout(resolve, 150));
    }
  };

  const handleUpload = (file: File) => {
    if (selectedAsset && onUploadShotAsset) onUploadShotAsset(activeShotIndex, selectedAsset.id, file);
  };

  if (!activeShot) return <div className="p-8 text-zinc-400">No shot selected.</div>;

  return (
    <div className="flex-1 overflow-y-auto p-6 flex flex-col gap-6 max-w-7xl mx-auto w-full">
      <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-zinc-800">
        <div>
          <div className="flex items-center gap-2"><Sliders className="w-5 h-5 text-amber-400" /><h2 className="text-xl font-editorial font-bold text-zinc-100 uppercase tracking-tight">Physical Collage Composition Studio</h2></div>
          <p className="text-xs text-zinc-400 mt-1">Shot-level composition. One shot can contain 1–8 independent image assets, each with its own motion.</p>
        </div>
        <div className="flex items-center gap-1.5 bg-zinc-900 p-1 rounded-lg border border-zinc-800 overflow-x-auto">
          {project.shots.map((s, idx) => <button key={s.shot_id} onClick={() => setActiveShotIndex(idx)} className={`px-3 py-1 rounded text-xs font-mono whitespace-nowrap ${activeShotIndex===idx?'bg-amber-400 text-zinc-950 font-bold':'text-zinc-400 hover:text-zinc-200'}`}>Shot {String(idx+1).padStart(2,'0')}</button>)}
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-[280px_minmax(0,1fr)_320px] gap-5">
        <aside className="bg-zinc-900 border border-zinc-800 rounded-xl p-4 flex flex-col gap-3">
          <div className="flex items-center justify-between"><span className="text-xs font-mono font-bold uppercase text-amber-400">Assets in Shot</span><span className="text-[10px] text-zinc-500">{assets.length}/{recipe.maxAssets}</span></div>
          <div className="text-[10px] leading-relaxed text-zinc-500">{recipe.description}</div>
          {assets.map((asset, idx) => <button key={asset.id} onClick={() => setSelectedAssetId(asset.id)} className={`text-left p-3 rounded-lg border transition ${selectedAsset?.id===asset.id?'border-amber-400 bg-amber-400/10':'border-zinc-800 bg-zinc-950 hover:border-zinc-700'}`}>
            <div className="flex items-center gap-2"><GripVertical className="w-3 h-3 text-zinc-600"/><span className="text-xs font-mono text-zinc-200">{idx+1}. {asset.role}</span><span className="ml-auto text-[9px] text-zinc-500">{asset.status||'pending'}</span></div>
            <div className="text-[10px] text-zinc-500 mt-1 truncate">{motionNames[asset.motion] || asset.motion}</div>
          </button>)}
          <div className="flex gap-2">
            <button onClick={prepareComposition} className="flex-1 flex items-center justify-center gap-1.5 px-2 py-2 bg-amber-500 hover:bg-amber-400 text-zinc-950 rounded-lg font-mono text-[10px] font-bold"><Wand2 className="w-3.5 h-3.5"/>Prepare</button>
            <button onClick={addAsset} disabled={assets.length>=recipe.maxAssets} className="px-3 py-2 bg-zinc-800 hover:bg-zinc-700 disabled:opacity-40 rounded-lg"><Plus className="w-4 h-4"/></button>
          </div>
        </aside>

        <main className="flex flex-col gap-5">
          <section className="bg-zinc-900 border border-zinc-800 rounded-xl p-5 flex flex-col gap-4">
            <div className="flex items-center justify-between"><span className="text-xs font-mono font-bold uppercase tracking-wider text-amber-400"><Scissors className="inline w-3.5 h-3.5 mr-1"/>Physical Collage & Stop-Motion Parameters</span><span className="text-[10px] font-mono text-zinc-500">AI Auto composition</span></div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <label className="flex flex-col gap-1.5"><span className="text-xs font-mono text-zinc-400">Layout Preset</span><select value={activeShot.layout} onChange={e=>handleLayoutChange(e.target.value as LayoutID)} className="bg-zinc-950 border border-zinc-700 rounded-lg p-2.5 text-xs font-mono text-zinc-200">{VOX_LAYOUTS.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>
              <label className="flex flex-col gap-1.5"><span className="text-xs font-mono text-zinc-400">Primary Motion</span><select value={selectedAsset?.motion || activeShot.composition?.primaryMotion || 'paper_drop'} onChange={e=>handleMotionChange(e.target.value as MotionID)} className="bg-zinc-950 border border-zinc-700 rounded-lg p-2.5 text-xs font-mono text-zinc-200">{VOX_MOTIONS.map(m=><option key={m.id} value={m.id}>{m.name} ({m.category})</option>)}</select></label>
              <label className="flex flex-col gap-1.5"><span className="text-xs font-mono text-zinc-400">Aged Paper Background</span><select value={activeShot.background.type} onChange={e=>onUpdateShot(activeShotIndex,{background:{...activeShot.background,type:e.target.value as any}})} className="bg-zinc-950 border border-zinc-700 rounded-lg p-2.5 text-xs font-mono text-zinc-200"><option value="newsprint">Vintage Newsprint with Columns</option><option value="archival">Archival Document Cream</option><option value="map">Vintage Cartographic Map</option><option value="corkboard">Investigation Corkboard</option><option value="cream_aged">Clean Aged Parchment</option></select></label>
              <label className="flex flex-col gap-1.5"><span className="text-xs font-mono text-zinc-400">Physical Border</span><select value={activeShot.composition?.border || 'scissor_cut'} onChange={e=>onUpdateShot(activeShotIndex,{composition:{...(activeShot.composition || {layout:activeShot.layout,background:activeShot.background.type,primaryMotion:'paper_drop'}),border:e.target.value as PhysicalBorderID}})} className="bg-zinc-950 border border-zinc-700 rounded-lg p-2.5 text-xs font-mono text-zinc-200"><option value="scissor_cut">Irregular Scissor-Cut Edge</option><option value="clean_edge">Clean Edge</option></select></label>
            </div>
            <div className="rounded-lg bg-zinc-950 border border-zinc-800 p-3 text-[10px] text-zinc-400"><Info className="inline w-3 h-3 mr-1 text-amber-400"/>{getMotionHelp(selectedAsset?.motion || activeShot.composition?.primaryMotion || 'paper_drop')}</div>
            {compositionErrors.length>0 ? <div className="rounded-lg border border-red-900/60 bg-red-950/20 p-3 text-xs text-red-300"><AlertCircle className="inline w-3.5 h-3.5 mr-1"/>{compositionErrors[0]}</div> : <div className="rounded-lg border border-emerald-900/50 bg-emerald-950/20 p-3 text-xs text-emerald-300"><CheckCircle2 className="inline w-3.5 h-3.5 mr-1"/>Composition asset count is valid for {recipe.name}.</div>}
          </section>

          <section className="bg-zinc-900 border border-zinc-800 rounded-xl p-5 flex flex-col gap-4">
            <div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs font-mono font-bold uppercase text-zinc-300">Asset Generator</span><div className="flex gap-2"><button onClick={prepareComposition} className="px-3 py-2 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-xs font-mono">Build Required Assets</button><button onClick={generateAll} className="px-3 py-2 rounded-lg bg-amber-500 hover:bg-amber-400 text-zinc-950 text-xs font-mono font-bold">Generate All Missing</button></div></div>
            <div className="text-[10px] text-zinc-500">For Photo Stack Land this panel intentionally contains multiple images. Each card is a separate AI-generated or uploaded asset; the compositor combines them into one shot.</div>
            <textarea value={promptText} onChange={e=>setPromptText(e.target.value)} onBlur={()=>selectedAsset&&updateAsset(selectedAsset.id,{assetPrompt:promptText})} rows={5} className="w-full bg-zinc-950 border border-zinc-700 rounded-lg p-3 text-zinc-200 font-mono text-xs leading-relaxed" placeholder="Describe this specific evidence asset..."/>
            <input value={negativePrompt} onChange={e=>setNegativePrompt(e.target.value)} className="w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-2 text-zinc-400 font-mono text-xs"/>
            <div className="flex flex-wrap gap-2">
              <button disabled={!selectedAsset || generatingAssetKey===`${activeShotIndex}_${selectedAsset?.id}`} onClick={()=>selectedAsset&&generateOne(selectedAsset)} className="flex items-center gap-2 px-4 py-2 bg-amber-500 hover:bg-amber-400 disabled:opacity-40 text-zinc-950 rounded-lg font-mono text-xs font-bold"><Sparkles className="w-3.5 h-3.5"/>{generatingAssetKey===`${activeShotIndex}_${selectedAsset?.id}`?'Generating...':'Generate Selected'}</button>
              <input type="file" accept="image/*" ref={fileInputRef} className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)handleUpload(f);e.currentTarget.value='';}}/>
              <button disabled={!selectedAsset} onClick={()=>fileInputRef.current?.click()} className="flex items-center gap-2 px-3 py-2 bg-zinc-800 hover:bg-zinc-700 disabled:opacity-40 text-zinc-300 rounded-lg font-mono text-xs"><Upload className="w-3.5 h-3.5"/>Upload to Selected</button>
              <button disabled={!selectedAsset || assets.length<=1} onClick={()=>selectedAsset&&removeAsset(selectedAsset.id)} className="flex items-center gap-2 px-3 py-2 bg-zinc-800 hover:bg-red-950 text-zinc-400 rounded-lg font-mono text-xs"><Trash2 className="w-3.5 h-3.5"/>Remove</button>
            </div>
          </section>
        </main>

        <aside className="bg-zinc-900 border border-zinc-800 rounded-xl p-5 flex flex-col gap-4">
          <span className="text-xs font-mono font-bold uppercase text-zinc-400">Selected Asset</span>
          <div className="w-full aspect-4/3 bg-zinc-950 rounded-lg border border-zinc-800 flex items-center justify-center overflow-hidden p-4">{selectedAsset?.source?<img src={selectedAsset.source} alt="Selected collage asset" className="max-w-full max-h-full object-contain filter drop-shadow-lg"/>:<div className="text-center text-zinc-600 font-mono text-xs"><Layers className="w-8 h-8 mx-auto mb-2"/>No image loaded</div>}</div>
          {selectedAsset && <div className="flex flex-col gap-2 text-xs font-mono bg-zinc-950/60 p-3 rounded-lg border border-zinc-800/80"><div className="flex justify-between"><span className="text-zinc-500">Role</span><span className="text-zinc-200 uppercase">{selectedAsset.role}</span></div><div className="flex justify-between"><span className="text-zinc-500">Status</span><span className="text-zinc-200">{selectedAsset.status||'pending'}</span></div><div className="flex justify-between"><span className="text-zinc-500">Motion</span><span className="text-amber-400">{motionNames[selectedAsset.motion]||selectedAsset.motion}</span></div><div className="flex justify-between"><span className="text-zinc-500">Start</span><span className="text-zinc-200">{selectedAsset.start.toFixed(2)}s</span></div></div>}
          <div className="rounded-lg border border-zinc-800 p-3 text-[10px] leading-relaxed text-zinc-500"><strong className="text-zinc-300">How this works:</strong> Layout defines how many visual resources are needed. Assets are the resources. Motion animates each resource. Graphics such as arrows/strings are separate procedural layers. The final video is composited from all of them.</div>
        </aside>
      </div>
    </div>
  );
};
