import React,{useState} from 'react';
import {Layers,Move3D,Film,RotateCcw,Info,Sparkles,Camera,Type,CheckCircle2,ChevronRight,SlidersHorizontal} from 'lucide-react';
import {PhysicalCollageParams,Shot} from '../types.ts';
import {VOX_LAYOUTS,VOX_MOTIONS} from '../presets/index.ts';

const DEFAULTS:PhysicalCollageParams={enabled:true,paperLift:35,shadowDepth:45,edgeRoughness:20,tapeStrength:60,depthParallax:18,stopMotion:true,frameStep:2,rotationJitter:3,positionJitter:2,settleAmount:70,holdFrames:2};
const tabs=[
 {id:'director',label:'AI Director',icon:Sparkles},
 {id:'layout',label:'Bố cục',icon:Layers},
 {id:'motion',label:'Motion',icon:Move3D},
 {id:'camera',label:'Camera',icon:Camera},
 {id:'layers',label:'Layers',icon:SlidersHorizontal},
 {id:'physical',label:'Vật lý',icon:Move3D},
 {id:'text',label:'Chữ',icon:Type},
] as const;
type TabId=typeof tabs[number]['id'];

interface Props{shot:Shot;onUpdate:(patch:Partial<Shot>)=>void;lang?:'vi'|'en';}
const layoutName=(id:string)=>VOX_LAYOUTS.find(x=>x.id===id)?.name||id;
const motionName=(id:string)=>VOX_MOTIONS.find(x=>x.id===id)?.name||id;

export const PhysicalCollageToolDock:React.FC<Props>=({shot,onUpdate})=>{
 const [tab,setTab]=useState<TabId>('director');
 const p={...DEFAULTS,...shot.physicalCollage};
 const hero=shot.assets.find(a=>a.role==='hero')||shot.assets[0];
 const currentMotion=hero?.motion||shot.composition?.primaryMotion||'paper_drop';
 const update=(key:keyof PhysicalCollageParams,value:number|boolean)=>onUpdate({physicalCollage:{...p,[key]:value} as PhysicalCollageParams});
 const chooseLayout=(id:any)=>onUpdate({layout:id,composition:{...shot.composition,layout:id}});
 const chooseMotion=(id:any)=>{if(!hero)return;onUpdate({assets:shot.assets.map(a=>a.id===hero.id?{...a,motion:id}:a),composition:{...shot.composition,primaryMotion:id}})};
 const Slider=({label,value,min,max,step=1,onChange,help}:{label:string;value:number;min:number;max:number;step?:number;onChange:(v:number)=>void;help:string})=><div className="space-y-1.5"><div className="flex items-center justify-between"><span className="text-[11px] text-zinc-300">{label}</span><span className="min-w-8 text-right text-[10px] font-mono text-amber-400">{value}</span></div><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))} className="w-full accent-amber-500"/><p className="text-[9px] leading-3 text-zinc-600">{help}</p></div>;
 const Preset=({title,sub,active,onClick}:{title:string;sub:string;active:boolean;onClick:()=>void})=><button onClick={onClick} className={`w-full text-left rounded-lg border p-2.5 transition ${active?'border-amber-500/70 bg-amber-500/10':'border-zinc-800 bg-zinc-900/70 hover:border-zinc-700 hover:bg-zinc-900'}`}><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${active?'bg-amber-400':'bg-zinc-700'}`}/><span className="text-[11px] font-semibold text-zinc-100">{title}</span>{active&&<CheckCircle2 className="ml-auto h-3.5 w-3.5 text-amber-400"/>}</div><div className="mt-1 pl-4 text-[9px] text-zinc-500">{sub}</div></button>;
 return <aside className="w-full overflow-hidden rounded-2xl border border-zinc-800 bg-[#0c0c0e] shadow-2xl shadow-black/30">
  <div className="border-b border-zinc-800 bg-zinc-950/90 px-3 pt-3"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold tracking-wide text-zinc-100"><span className="rounded-md bg-amber-500/10 p-1.5 text-amber-400"><Sparkles className="h-3.5 w-3.5"/></span>AI VISUAL INSPECTOR</div><div className="mt-1 text-[9px] text-zinc-600">SHOT {String(shot.order).padStart(2,'0')} • {shot.duration}s • {shot.assets.length} assets</div></div><button onClick={()=>onUpdate({physicalCollage:DEFAULTS})} title="Đặt lại vật lý" className="rounded-lg border border-zinc-800 p-2 text-zinc-600 hover:text-amber-300"><RotateCcw className="h-3.5 w-3.5"/></button></div><div className="mt-3 flex gap-1 overflow-x-auto pb-2 scrollbar-thin">{tabs.map(t=>{const Icon=t.icon;return <button key={t.id} onClick={()=>setTab(t.id)} className={`flex shrink-0 items-center gap-1.5 rounded-md px-2.5 py-1.5 text-[9px] font-semibold transition ${tab===t.id?'bg-zinc-100 text-zinc-950':'text-zinc-500 hover:bg-zinc-900 hover:text-zinc-200'}`}><Icon className="h-3 w-3"/>{t.label}</button>})}</div></div>
  <div className="max-h-[calc(100vh-210px)] overflow-y-auto p-3">
   {tab==='director'&&<div className="space-y-3"><div className="rounded-xl border border-amber-900/40 bg-gradient-to-br from-amber-950/30 to-zinc-950 p-3"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-amber-300"><Sparkles className="h-3.5 w-3.5"/>Visual Director</div><p className="mt-2 text-[11px] leading-4 text-zinc-400">Điều khiển nhanh phong cách của shot. Chọn preset, sau đó tinh chỉnh chi tiết ở các tab bên cạnh.</p><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-lg bg-zinc-950/80 p-2"><div className="text-[8px] uppercase text-zinc-600">Bố cục</div><div className="mt-1 truncate text-[10px] font-semibold text-zinc-200">{layoutName(shot.layout)}</div></div><div className="rounded-lg bg-zinc-950/80 p-2"><div className="text-[8px] uppercase text-zinc-600">Motion</div><div className="mt-1 truncate text-[10px] font-semibold text-zinc-200">{motionName(currentMotion)}</div></div></div></div><div className="space-y-2"><div className="flex items-center justify-between"><span className="text-[10px] font-semibold text-zinc-300">Trạng thái shot</span><span className="flex items-center gap-1 text-[9px] text-emerald-400"><CheckCircle2 className="h-3 w-3"/>Sẵn sàng chỉnh</span></div>{[['Ảnh hero',hero?.source?'Đã có':'Chưa có'],['Nền',shot.background.type],['Vật lý',p.enabled?'Đang bật':'Đang tắt']].map(([a,b])=><div key={a} className="flex items-center justify-between border-b border-zinc-900 py-2 text-[10px]"><span className="text-zinc-500">{a}</span><span className="text-zinc-300">{b}</span></div>)}</div><button onClick={()=>setTab('physical')} className="flex w-full items-center justify-between rounded-lg border border-zinc-800 bg-zinc-900 p-2.5 text-left hover:border-zinc-700"><span><span className="block text-[10px] font-semibold text-zinc-200">Tinh chỉnh chất liệu giấy</span><span className="block text-[9px] text-zinc-600">Bóng • mép • tape • parallax • stop-motion</span></span><ChevronRight className="h-4 w-4 text-zinc-600"/></button></div>}
   {tab==='layout'&&<div className="space-y-2"><SectionTitle title="BỐ CỤC CẢNH" desc="Chọn cách sắp xếp vật thể trên canvas."/>{VOX_LAYOUTS.map(x=><Preset key={x.id} title={x.name} sub={x.description} active={shot.layout===x.id} onClick={()=>chooseLayout(x.id)}/>)}</div>}
   {tab==='motion'&&<div className="space-y-2"><SectionTitle title="CHUYỂN ĐỘNG" desc="Chọn cách ảnh, giấy và chữ xuất hiện."/>{VOX_MOTIONS.map(x=><Preset key={x.id} title={x.name} sub={x.description} active={currentMotion===x.id} onClick={()=>chooseMotion(x.id)}/>)}</div>}
   {tab==='camera'&&<div className="space-y-3"><SectionTitle title="CAMERA" desc="Điều chỉnh cảm giác máy quay mà không phá bố cục."/><div className="grid grid-cols-3 gap-2">{['Khóa','Push In','Pull Out'].map((x,i)=><button key={x} className={`rounded-lg border p-2 text-[9px] ${i===0?'border-amber-500/50 bg-amber-500/10 text-amber-300':'border-zinc-800 bg-zinc-900 text-zinc-400'}`}>{x}</button>)}</div><Slider label="Độ phóng" value={0} min={-30} max={30} onChange={()=>{}} help="Điều chỉnh nhẹ kích thước khung hình."/><Slider label="Độ lệch ngang" value={0} min={-20} max={20} onChange={()=>{}} help="Tạo cảm giác camera dịch chuyển."/></div>}
   {tab==='layers'&&<div className="space-y-2"><SectionTitle title="LỚP CẢNH" desc="Thứ tự các thành phần trong shot."/>{shot.assets.map((a,i)=><div key={a.id} className="flex items-center gap-2 rounded-lg border border-zinc-800 bg-zinc-900/70 p-2.5"><span className="w-5 text-center text-[9px] font-mono text-zinc-600">{i+1}</span><div className="h-7 w-10 overflow-hidden rounded bg-zinc-950">{a.source&&<img src={a.source} className="h-full w-full object-cover"/>}</div><div className="min-w-0 flex-1"><div className="truncate text-[10px] font-semibold text-zinc-200">{a.role}</div><div className="text-[8px] text-zinc-600">{a.type} • {a.motion}</div></div><span className="text-[9px] text-zinc-600">{Math.round(a.scale*100)}%</span></div>)}</div>}
   {tab==='physical'&&<div className="space-y-4"><SectionTitle title="CHẤT LIỆU VẬT LÝ" desc="Làm ảnh giống giấy, ảnh in và collage thật."/><label className="flex items-center justify-between rounded-lg border border-zinc-800 bg-zinc-900 p-2.5"><span className="flex items-center gap-2 text-[10px] font-semibold text-zinc-200"><Move3D className="h-3.5 w-3.5 text-sky-400"/>Bật hiệu ứng vật lý</span><input type="checkbox" checked={p.enabled} onChange={e=>update('enabled',e.target.checked)} className="accent-amber-500"/></label><Slider label="Độ nhấc giấy" value={p.paperLift} min={0} max={100} onChange={v=>update('paperLift',v)} help="Độ nổi của tờ giấy so với mặt bàn."/><Slider label="Độ sâu bóng" value={p.shadowDepth} min={0} max={100} onChange={v=>update('shadowDepth',v)} help="Bóng sâu hơn giúp tách các lớp collage."/><Slider label="Độ thô mép giấy" value={p.edgeRoughness} min={0} max={100} onChange={v=>update('edgeRoughness',v)} help="Tạo cảm giác mép cắt thủ công."/><Slider label="Độ bám băng keo" value={p.tapeStrength} min={0} max={100} onChange={v=>update('tapeStrength',v)} help="Mức độ nhìn thấy của tape giữ ảnh."/><Slider label="Chiều sâu lớp" value={p.depthParallax} min={0} max={50} onChange={v=>update('depthParallax',v)} help="Khoảng cách thị giác giữa các lớp."/><div className="border-t border-zinc-800 pt-3"><div className="mb-2 flex items-center gap-2 text-[10px] font-bold text-red-300"><Film className="h-3.5 w-3.5"/>STOP-MOTION</div><label className="mb-3 flex items-center justify-between rounded-lg border border-red-950/60 bg-red-950/20 p-2.5"><span className="text-[10px] text-zinc-200">Bật từng khung hình</span><input type="checkbox" checked={p.stopMotion} onChange={e=>update('stopMotion',e.target.checked)} className="accent-red-500"/></label><div className="space-y-3"><Slider label="Bước khung hình" value={p.frameStep} min={1} max={6} onChange={v=>update('frameStep',v)} help="2–3 cho cảm giác stop-motion rõ."/><Slider label="Rung xoay" value={p.rotationJitter} min={0} max={12} onChange={v=>update('rotationJitter',v)} help="Lệch góc nhẹ giữa các frame."/><Slider label="Rung vị trí" value={p.positionJitter} min={0} max={12} onChange={v=>update('positionJitter',v)} help="Lệch vị trí tự nhiên giữa các frame."/><Slider label="Độ ổn định" value={p.settleAmount} min={0} max={100} onChange={v=>update('settleAmount',v)} help="Càng cao, vật thể càng nhanh đứng yên."/><Slider label="Giữ khung hình" value={p.holdFrames} min={0} max={8} onChange={v=>update('holdFrames',v)} help="Số frame giữ nguyên trước khi đổi pose."/></div></div><div className="flex gap-2 rounded-lg border border-amber-900/30 bg-amber-950/10 p-2.5"><Info className="h-3.5 w-3.5 shrink-0 text-amber-400"/><span className="text-[9px] leading-3.5 text-amber-200/80">Gợi ý documentary: Nhấc 35–50 • Bóng 45–65 • Parallax 15–25 • Stop-motion bước 2.</span></div></div>}
   {tab==='text'&&<div className="space-y-2"><SectionTitle title="KIỂU CHỮ" desc="Các lớp text đang có trong shot."/>{shot.text.map(t=><div key={t.id} className="rounded-lg border border-zinc-800 bg-zinc-900 p-2.5"><div className="flex justify-between"><span className="text-[9px] uppercase text-zinc-600">{t.role}</span><span className="text-[9px] text-amber-400">{t.style}</span></div><div className="mt-1 truncate text-[11px] font-semibold text-zinc-200">{t.content||'—'}</div></div>)}</div>}
  </div>
 </aside>;
};

const SectionTitle=({title,desc}:{title:string;desc:string})=><div className="mb-3"><div className="text-[10px] font-bold tracking-wider text-zinc-200">{title}</div><div className="mt-1 text-[9px] leading-3 text-zinc-600">{desc}</div></div>;
