import React, { useMemo, useState } from 'react';
import { FolderKanban, Sparkles, FileText, Layers, ArrowRight, Wand2, Search, ShieldCheck, Activity, SlidersHorizontal } from 'lucide-react';
import { Project } from '../types.ts';
import { Language, translations } from '../locales/translations.ts';
import { VISUAL_STYLES, VISUAL_STYLE_CATEGORIES, VisualDirectionMode, VisualStyleId } from '../visualDirector/StyleDirector.ts';
import { getVisualDirectorDiagnostics } from '../visualDirector/VisualDirectorDiagnostics.ts';

interface ProjectOverviewViewProps { project:Project; topic:string; setTopic:(val:string)=>void; duration:number; setDuration:(val:number)=>void; onGenerateStoryboard:()=>void; isGenerating:boolean; onJumpToCanvas:()=>void; lang?:Language; visualDirectionMode:VisualDirectionMode; manualVisualStyle:VisualStyleId; onVisualModeChange:(mode:VisualDirectionMode)=>void; onManualStyleChange:(style:VisualStyleId)=>void; }
const TOPIC_SUGGESTIONS_VI=['Ngày Thị Trường Phố Wall Sụp Đổ (1929)','Apollo 11: Báo động máy tính 1202','Bức Tường Berlin Sụp Đổ (1989)','Dự Án Manhattan: Thử Nghiệm Trinity (1945)','Thảm Kịch Tàu Titanic (1912)'];
const TOPIC_SUGGESTIONS_EN=['The Day Wall Street Crashed (1929)','Apollo 11: The 1202 Computer Alarm','The Fall of the Berlin Wall (1989)','The Manhattan Project Trinity Test (1945)','The Sinking of the Titanic (1912)'];

export const ProjectOverviewView:React.FC<ProjectOverviewViewProps>=({project,topic,setTopic,duration,setDuration,onGenerateStoryboard,isGenerating,onJumpToCanvas,lang='vi',visualDirectionMode,manualVisualStyle,onVisualModeChange,onManualStyleChange})=>{
 const t=translations[lang]; const suggestions=lang==='vi'?TOPIC_SUGGESTIONS_VI:TOPIC_SUGGESTIONS_EN; const selected=VISUAL_STYLES.find(s=>s.id===manualVisualStyle)||VISUAL_STYLES[0];
 const [query,setQuery]=useState(''); const [category,setCategory]=useState('Tất cả');
 const diagnostics=getVisualDirectorDiagnostics(project);
 const filtered=useMemo(()=>VISUAL_STYLES.filter(s=>{const q=query.trim().toLowerCase();const matchQ=!q||`${s.name} ${s.englishName} ${s.description} ${s.bestFor.join(' ')}`.toLowerCase().includes(q);const matchC=category==='Tất cả'||s.category===category;return matchQ&&matchC;}),[query,category]);
 const filteredGroups=VISUAL_STYLE_CATEGORIES.map(c=>({category:c,styles:filtered.filter(s=>s.category===c)})).filter(g=>g.styles.length);
 return <div className="flex-1 overflow-y-auto p-6 flex flex-col gap-6 max-w-6xl mx-auto w-full">
  <div className="flex items-center justify-between pb-4 border-b border-zinc-800"><div><div className="flex items-center gap-2"><FolderKanban className="w-5 h-5 text-amber-400"/><h2 className="text-xl font-editorial font-bold text-zinc-100 uppercase tracking-tight">AI Director & Visual Style Studio</h2></div><p className="text-xs text-zinc-400 mt-1">Thư viện style vật lý cho giấy, ảnh, hồ sơ, báo chí, bản đồ và điều tra. Style không chỉ đổi metadata — nó điều khiển layout, motion và material.</p></div><button onClick={onJumpToCanvas} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-amber-400 text-xs font-mono font-semibold transition">{lang==='vi'?'Mở Canvas':'Open Canvas'}<ArrowRight className="w-3.5 h-3.5"/></button></div>
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-2">
   {[['Style',diagnostics.totalStyles],['Nhóm',diagnostics.totalCategories],['Layout',diagnostics.uniqueLayouts],['Motion',diagnostics.uniqueMotions],['Cảnh',project.shots.length]].map(([label,value])=><div key={String(label)} className="bg-zinc-900 border border-zinc-800 rounded-lg p-3"><div className="text-[9px] uppercase font-mono text-zinc-500">{label}</div><div className="text-lg font-mono font-bold text-zinc-100 mt-1">{value}</div></div>)}
  </div>
  <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-5 flex flex-col gap-5">
   <div className="flex items-center justify-between"><span className="text-xs font-mono font-bold uppercase tracking-wider text-amber-400 flex items-center gap-2"><Sparkles className="w-4 h-4"/>AI Visual Director</span><span className="text-xs font-mono text-zinc-500">{project.shots.length} shots • {VISUAL_STYLES.length} styles</span></div>
   <div className="flex flex-col gap-1.5"><label className="text-xs font-mono text-zinc-300 font-semibold uppercase">{lang==='vi'?'Chủ đề phim tài liệu':'Documentary Topic'}</label><input type="text" value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. The Day Wall Street Crashed" className="w-full px-4 py-3 bg-zinc-950 border border-zinc-700 rounded-lg text-sm text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-amber-400 transition"/></div>
   <div className="flex flex-wrap items-center gap-2"><span className="text-[11px] font-mono text-zinc-500">{lang==='vi'?'Chủ đề nhanh:':'Fast presets:'}</span>{suggestions.map(p=><button key={p} onClick={()=>setTopic(p)} className="text-xs px-2.5 py-1 rounded bg-zinc-950 hover:bg-zinc-800 text-zinc-300 border border-zinc-800">{p}</button>)}</div>
   <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 border-t border-zinc-800 pt-4">
    <div><label className="text-xs font-mono text-zinc-400 font-semibold">{lang==='vi'?'Chế độ đạo diễn':'Director Mode'}</label><div className="grid grid-cols-3 gap-1 mt-1 bg-zinc-950 p-1 rounded border border-zinc-800">{(['auto','hybrid','manual'] as VisualDirectionMode[]).map(mode=><button key={mode} onClick={()=>onVisualModeChange(mode)} className={`py-2 rounded text-[10px] font-mono uppercase ${visualDirectionMode===mode?'bg-amber-400 text-zinc-950 font-bold':'text-zinc-400 hover:text-white'}`}>{mode==='auto'?'AI Auto':mode==='hybrid'?'Hybrid':'Manual'}</button>)}</div></div>
    <div><label className="text-xs font-mono text-zinc-400 font-semibold">{lang==='vi'?'Style khóa':'Locked Style'}</label><select value={manualVisualStyle} onChange={e=>onManualStyleChange(e.target.value)} className="mt-1 w-full bg-zinc-950 border border-zinc-800 rounded p-2 text-xs text-zinc-200">{VISUAL_STYLE_CATEGORIES.map(group=><optgroup key={group} label={group}>{VISUAL_STYLES.filter(s=>s.category===group).map(s=><option key={s.id} value={s.id}>{s.name} — {s.englishName||s.id}</option>)}</optgroup>)}</select></div>
    <div className="bg-zinc-950 border border-zinc-800 rounded p-3"><div className="flex items-center gap-2 text-xs font-mono text-amber-400"><Wand2 className="w-3.5 h-3.5"/>{selected.name}</div><div className="text-[11px] text-zinc-400 mt-1">{selected.category}</div><div className="text-[10px] text-zinc-600 mt-1">{selected.description||selected.bestFor.slice(0,3).join(' • ')}</div></div>
   </div>
   <div className="border-t border-zinc-800 pt-4 flex flex-col gap-3">
    <div className="flex items-center justify-between"><span className="text-xs font-mono font-bold text-zinc-300">THƯ VIỆN STYLE — TÌM KIẾM + LỌC</span><span className="text-[10px] text-zinc-600">{filtered.length}/{VISUAL_STYLES.length}</span></div>
    <div className="grid grid-cols-1 md:grid-cols-[1fr_auto] gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 w-3.5 h-3.5 text-zinc-600"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm: lật, hồ sơ, báo chí, ảnh, map, investigation..." className="w-full bg-zinc-950 border border-zinc-800 rounded px-9 py-2 text-xs text-zinc-200 outline-none focus:border-amber-400"/></div><div className="flex items-center gap-1 overflow-x-auto"><SlidersHorizontal className="w-3.5 h-3.5 text-zinc-600"/>{['Tất cả',...VISUAL_STYLE_CATEGORIES].map(c=><button key={c} onClick={()=>setCategory(c)} className={`whitespace-nowrap px-2 py-1.5 rounded text-[10px] font-mono border ${category===c?'border-amber-400 text-amber-300 bg-amber-500/10':'border-zinc-800 text-zinc-500 hover:text-zinc-200'}`}>{c}</button>)}</div></div>
    {filteredGroups.map(group=><div key={group.category}><div className="text-[11px] font-mono font-bold text-amber-400 mb-1.5">{group.category} <span className="text-zinc-600">({group.styles.length})</span></div><div className="flex flex-wrap gap-1.5">{group.styles.map(s=><button key={s.id} title={`${s.name} — ${s.description||s.englishName||''}`} onClick={()=>onManualStyleChange(s.id)} className={`text-[10px] px-2 py-1 rounded border transition ${manualVisualStyle===s.id?'border-amber-400 text-amber-300 bg-amber-500/10':'border-zinc-800 text-zinc-400 hover:border-zinc-600 hover:text-zinc-200'} ${project.shots.some(x=>x.visualStyle===s.id)?'ring-1 ring-red-500/30':''}`}>{s.name}</button>)}</div></div>)}
   </div>
   <div className="grid grid-cols-1 md:grid-cols-3 gap-3 border-t border-zinc-800 pt-4">
    <div className="bg-zinc-950 border border-zinc-800 rounded p-3"><div className="flex items-center gap-2 text-xs font-mono text-zinc-300"><ShieldCheck className="w-3.5 h-3.5 text-emerald-400"/>Visual Quality Gate</div><div className="text-[10px] text-zinc-500 mt-2">{diagnostics.warnings.length?diagnostics.warnings.join(' • '):'Không phát hiện cảnh báo visual repetition.'}</div></div>
    <div className="bg-zinc-950 border border-zinc-800 rounded p-3"><div className="flex items-center gap-2 text-xs font-mono text-zinc-300"><Activity className="w-3.5 h-3.5 text-amber-400"/>Style Diversity</div><div className="text-sm font-mono font-bold text-zinc-100 mt-2">{Math.round(diagnostics.styleCoverage*100)}% thư viện</div><div className="text-[10px] text-zinc-500">{diagnostics.repeatedStyles} style bị lặp trong sequence</div></div>
    <div className="bg-zinc-950 border border-zinc-800 rounded p-3"><div className="flex items-center gap-2 text-xs font-mono text-zinc-300"><Layers className="w-3.5 h-3.5 text-sky-400"/>Motion Coverage</div><div className="text-sm font-mono font-bold text-zinc-100 mt-2">{diagnostics.uniqueMotions} motion</div><div className="text-[10px] text-zinc-500">Motion vật lý được render trực tiếp trên Canvas</div></div>
   </div>
   <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 border-t border-zinc-800 pt-4">{[20,25,30,60].map(sec=><button key={sec} onClick={()=>setDuration(sec)} className={`py-2 rounded border text-xs font-mono ${duration===sec?'bg-amber-400 text-zinc-950 border-amber-400':'bg-zinc-950 text-zinc-400 border-zinc-800'}`}>{sec}s</button>)}</div>
   <div className="pt-3 border-t border-zinc-800 flex justify-end"><button onClick={onGenerateStoryboard} disabled={isGenerating||!topic.trim()} className="flex items-center gap-2 px-6 py-2.5 bg-red-600 hover:bg-red-500 text-white font-mono font-bold text-xs rounded-lg disabled:opacity-50"><Sparkles className={`w-4 h-4 ${isGenerating?'animate-spin':''}`}/>{isGenerating?'DIRECTING...':'GENERATE STORYBOARD + VISUAL DIRECTION'}</button></div>
  </div>
  <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div className="bg-zinc-900 border border-zinc-800 rounded-xl p-4"><div className="flex items-center justify-between mb-3"><span className="text-xs font-mono font-bold uppercase tracking-wider text-zinc-300 flex items-center gap-1.5"><Layers className="w-3.5 h-3.5 text-amber-400"/>Visual Sequence</span><span className="text-xs font-mono text-amber-400">{project.shots.length} Shots</span></div><div className="flex flex-col gap-1.5">{project.shots.map(s=><div key={s.shot_id} className="flex items-center justify-between text-xs font-mono bg-zinc-950/60 p-2 rounded border border-zinc-800/80 text-zinc-300"><span>Shot {String(s.order).padStart(2,'0')} • {VISUAL_STYLES.find(v=>v.id===s.visualStyle)?.name||s.visualStyle||'VOX Cổ điển'} • {s.layout}</span><span className="text-zinc-500">{s.duration}s</span></div>)}</div></div>
   <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-4 flex flex-col gap-3"><div className="flex items-center justify-between"><span className="text-xs font-mono font-bold uppercase tracking-wider text-zinc-300 flex items-center gap-1.5"><FileText className="w-3.5 h-3.5 text-amber-400"/>Voiceover Narration</span><span className="text-xs font-mono text-emerald-400">{project.voiceUrl?'Audio Synced':'Ready for TTS'}</span></div><p className="text-xs font-mono text-zinc-300 leading-relaxed bg-zinc-950/60 p-3 rounded border border-zinc-800/80 flex-1">"{project.script}"</p></div></div>
 </div>;
};
