import React,{useState,useRef} from 'react';
import {Layers,RefreshCw,Edit3,Scissors,Upload,Sparkles,Loader2,CheckCircle2,AlertCircle} from 'lucide-react';
import {Project,Shot} from '../types.ts';
import {VOX_LAYOUTS,VOX_MOTIONS} from '../presets/index.ts';

interface Props{project:Project;activeShotIndex:number;setActiveShotIndex:(idx:number)=>void;onUpdateShot:(index:number,updated:Partial<Shot>)=>void;onRegenerateShotLayout:(index:number)=>void;onRegenerateShotMotion:(index:number)=>void;onGenerateShotAsset?:(shotIndex:number,assetId:string)=>void;onUploadShotAsset?:(shotIndex:number,assetId:string,file:File)=>void;generatingAssetKey?:string|null;}
const layoutName=(id:string)=>VOX_LAYOUTS.find(x=>x.id===id)?.name||id;
const motionName=(id:string)=>VOX_MOTIONS.find(x=>x.id===id)?.name||id;

export const StoryboardView:React.FC<Props>=({project,activeShotIndex,setActiveShotIndex,onUpdateShot,onRegenerateShotLayout,onRegenerateShotMotion,onGenerateShotAsset,onUploadShotAsset,generatingAssetKey})=>{
 const [editing,setEditing]=useState<number|null>(null);const [headline,setHeadline]=useState('');const [date,setDate]=useState('');const [prompt,setPrompt]=useState('');const [notice,setNotice]=useState<Record<number,string>>({});const refs=useRef<Record<string,HTMLInputElement|null>>({});
 const startEdit=(i:number,s:Shot)=>{setEditing(i);setHeadline(s.text.find(t=>t.role==='headline'||t.role==='big_number')?.content||'');setDate(s.text.find(t=>t.role==='date'||t.role==='label')?.content||'');setPrompt(s.assets.find(a=>a.role==='hero')?.assetPrompt||'');};
 const save=(i:number)=>{const s=project.shots[i];onUpdateShot(i,{text:s.text.map(t=>t.role==='headline'||t.role==='big_number'?{...t,content:headline}:t.role==='date'||t.role==='label'?{...t,content:date}:t),assets:s.assets.map(a=>a.role==='hero'&&prompt?{...a,assetPrompt:prompt}:a)});setEditing(null);};
 const changeLayout=(i:number)=>{const s=project.shots[i];const ids=VOX_LAYOUTS.map(x=>x.id);const n=ids[(Math.max(0,ids.indexOf(s.layout))+1)%ids.length];setNotice(v=>({...v,[i]:`LAYOUT đã đổi: ${layoutName(s.layout)} → ${layoutName(n)}`}));onRegenerateShotLayout(i);};
 const changeMotion=(i:number)=>{const s=project.shots[i];const hero=s.assets.find(a=>a.role==='hero')||s.assets[0];const current=hero?.motion||s.composition?.primaryMotion||'paper_drop';const ids=VOX_MOTIONS.map(x=>x.id);const n=ids[(Math.max(0,ids.indexOf(current))+1)%ids.length];setNotice(v=>({...v,[i]:`MOTION đã đổi: ${motionName(current)} → ${motionName(n)}`}));onRegenerateShotMotion(i);};
 return <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-4 shadow-lg flex flex-col gap-4"><div className="flex items-center justify-between border-b border-zinc-800 pb-3"><div className="flex items-center gap-2"><Layers className="w-4 h-4 text-amber-400"/><h2 className="font-editorial text-lg font-bold text-zinc-100 uppercase">Storyboard & Bộ máy tài sản</h2></div><span className="text-[10px] font-mono text-zinc-500">Mỗi thao tác Layout/Motion đều hiển thị thay đổi</span></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
 {project.shots.map((shot,i)=>{const active=activeShotIndex===i;const hero=shot.assets.find(a=>a.role==='hero')||shot.assets[0];const generating=generatingAssetKey===`${i}_${hero?.id}`||hero?.status==='generating';const ready=hero?.status==='ready'&&!!hero.source;const motion=hero?.motion||shot.composition?.primaryMotion||'paper_drop';return <div key={shot.shot_id} onClick={()=>setActiveShotIndex(i)} className={`border rounded-xl p-3 flex flex-col gap-3 cursor-pointer ${active?'bg-zinc-950 border-amber-500/80':'bg-zinc-950/60 border-zinc-800'}`}>
 <input type="file" accept="image/*" ref={el=>(refs.current[`${i}_${hero?.id}`]=el)} className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f&&hero&&onUploadShotAsset)onUploadShotAsset(i,hero.id,f)}}/>
 <div className="flex items-center justify-between"><span className="text-xs font-mono font-bold text-zinc-200">SHOT {String(i+1).padStart(2,'0')}</span><span className="text-[10px] font-mono text-zinc-500">{shot.duration}s</span></div>
 <div className="grid grid-cols-2 gap-1.5"><div className="rounded bg-red-950/50 border border-red-900/60 p-2"><div className="text-[9px] text-red-300 uppercase">Bố cục / Layout</div><div className="text-[11px] text-zinc-100 font-bold mt-1">{layoutName(shot.layout)}</div></div><div className="rounded bg-sky-950/40 border border-sky-900/60 p-2"><div className="text-[9px] text-sky-300 uppercase">Chuyển động / Motion</div><div className="text-[11px] text-zinc-100 font-bold mt-1">{motionName(motion)}</div></div></div>
 <div className="bg-zinc-900 rounded p-2.5 border border-zinc-800"><p className="text-xs text-zinc-300 italic line-clamp-2">“{shot.narration}”</p></div>
 <div className="bg-zinc-900 rounded-lg p-2.5 border border-zinc-800"><div className="flex justify-between items-center"><span className="text-[10px] text-amber-400 font-mono"><Scissors className="w-3 h-3 inline mr-1"/>Ảnh / Cutout</span><span className="text-[9px] text-zinc-500">{generating?'ĐANG TẠO':ready?'SẴN SÀNG':'CHỜ'}</span></div><div className="h-24 mt-2 bg-zinc-950 rounded border border-zinc-800 flex items-center justify-center overflow-hidden">{hero?.source?<img src={hero.source} className="max-h-20 max-w-full object-contain"/>:<div className="text-[10px] text-zinc-600 text-center">Chưa có ảnh<br/>AI Director đã chuẩn bị prompt</div>}</div><div className="flex gap-1 mt-2">{onGenerateShotAsset&&hero&&<button onClick={e=>{e.stopPropagation();onGenerateShotAsset(i,hero.id)}} disabled={generating} className="flex-1 py-1.5 rounded bg-amber-600 text-zinc-950 text-[10px] font-bold">{generating?<Loader2 className="w-3 h-3 animate-spin mx-auto"/>:<Sparkles className="w-3 h-3 inline mr-1"/>}{ready?'Tạo lại':'Tạo ảnh'}</button>}<button onClick={e=>{e.stopPropagation();hero&&refs.current[`${i}_${hero.id}`]?.click()}} className="px-2 rounded bg-zinc-800 text-[10px] text-zinc-300"><Upload className="w-3 h-3 inline mr-1"/>Tải ảnh</button></div></div>
 {editing===i?<div className="space-y-2 bg-zinc-900 p-2 rounded" onClick={e=>e.stopPropagation()}><input value={date} onChange={e=>setDate(e.target.value)} placeholder="Ngày / nhãn" className="w-full bg-zinc-950 border border-zinc-700 rounded p-1.5 text-xs"/><input value={headline} onChange={e=>setHeadline(e.target.value)} placeholder="Tiêu đề" className="w-full bg-zinc-950 border border-zinc-700 rounded p-1.5 text-xs"/><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Prompt hình ảnh" className="w-full bg-zinc-950 border border-zinc-700 rounded p-1.5 text-xs"/><div className="flex justify-end gap-1"><button onClick={()=>setEditing(null)} className="px-2 py-1 text-[10px] text-zinc-400">Hủy</button><button onClick={()=>save(i)} className="px-2 py-1 text-[10px] bg-amber-500 text-zinc-950 rounded font-bold">Lưu</button></div></div>:<div className="text-[10px] text-zinc-500 truncate">Tiêu đề: <span className="text-zinc-200">{shot.text.find(t=>t.role==='headline'||t.role==='big_number')?.content||'Chưa có'}</span></div>}
 <div className="flex gap-1 pt-2 border-t border-zinc-800" onClick={e=>e.stopPropagation()}><button onClick={()=>changeLayout(i)} className="flex-1 py-2 rounded bg-zinc-800 hover:bg-zinc-700 text-zinc-200 text-[10px] font-bold"><RefreshCw className="w-3 h-3 inline mr-1"/>LAYOUT — đổi bố cục</button><button onClick={()=>changeMotion(i)} className="flex-1 py-2 rounded bg-zinc-800 hover:bg-zinc-700 text-zinc-200 text-[10px] font-bold"><RefreshCw className="w-3 h-3 inline mr-1"/>MOTION — đổi chuyển động</button><button onClick={()=>startEdit(i,shot)} className="px-2 rounded bg-zinc-800 text-zinc-300"><Edit3 className="w-3 h-3"/></button></div>
 {notice[i]&&<div className="rounded border border-emerald-800 bg-emerald-950/40 p-2 text-[10px] text-emerald-300 flex items-start gap-1.5"><CheckCircle2 className="w-3.5 h-3.5 shrink-0"/>{notice[i]}</div>}
 <div className="text-[9px] text-zinc-600">Layout = sắp xếp vật thể. Motion = cách vật thể xuất hiện/chuyển động. Bấm lại để chuyển sang preset tiếp theo.</div>
 </div>})}</div></div>;
};
