import { Shot, VisualAsset, TextElement, GraphicElement } from '../types.ts';
import { calculateMotionTransform } from './motionEngine.ts';
import { drawAgedPaperBackground, drawMaskingTape, drawArchivalStamp, drawRedString, drawRedMarkerArrow } from './paperAssets.ts';
import { getCachedImage, getOrLoadDecodedImage, getHalftonePatternCanvas } from './assetCache.ts';
import { getClientVisualTheme } from '../visualDirector/StyleVisualTheme.ts';
import { getPhysicalLayoutFrame } from '../visualDirector/CompositionEngine.ts';
export { getCachedImage };
export async function preloadShotImages(shot:Shot):Promise<void>{await Promise.all((shot.assets||[]).filter(a=>a.source).map(a=>getOrLoadDecodedImage(a.source)));}
function rr(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){c.beginPath();if(r&&'roundRect' in c)c.roundRect(x,y,w,h,r);else c.rect(x,y,w,h);}
function bg(c:CanvasRenderingContext2D,s:Shot,w:number,h:number){c.clearRect(0,0,w,h);drawAgedPaperBackground(c,w,h,s.composition?.background||s.background?.type||'newsprint');if(s.layout==='map'){c.save();c.strokeStyle='rgba(70,50,30,.2)';c.setLineDash([10,10]);for(let x=80;x<w;x+=180){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=80;y<h;y+=150){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}c.restore();}}
function panel(c:CanvasRenderingContext2D,t:any,x:number,y:number,w:number,h:number){if(t.shadow){c.save();c.shadowColor='rgba(0,0,0,.28)';c.shadowBlur=18;c.shadowOffsetX=8;c.shadowOffsetY=10;c.fillStyle=t.panel;rr(c,x,y,w,h,t.radius);c.fill();c.restore();}c.fillStyle=t.panel;rr(c,x,y,w,h,t.radius);c.fill();c.strokeStyle=t.accent;c.globalAlpha=.4;rr(c,x,y,w,h,t.radius);c.stroke();c.globalAlpha=1;}
function asset(c:CanvasRenderingContext2D,s:Shot,a:VisualAsset,i:number,n:number,time:number,w:number,h:number,t:any){const m=calculateMotionTransform(a.motion,time,a.start);if(m.opacity<=0)return;const f=getPhysicalLayoutFrame(s.layout,i,n,a.role),x=f.x/100*w,y=f.y/100*h,iw=f.w/100*w,ih=f.h/100*h;c.save();c.globalAlpha=m.opacity;c.translate(x+m.offsetX,y+m.offsetY);c.rotate(((a.rotation||0)+m.rotation)*Math.PI/180);c.scale((a.scale||1)*m.scale,(a.scale||1)*m.scale);const px=-iw/2,py=-ih/2;if(f.panel)panel(c,t,px,py,iw,ih);const pad=14,img=getCachedImage(a.source);if(img&&img.complete&&img.naturalWidth){c.save();rr(c,px+pad,py+pad,iw-pad*2,ih-pad*2,Math.max(0,t.radius-6));c.clip();const ia=img.naturalWidth/img.naturalHeight,ba=(iw-pad*2)/(ih-pad*2);let dw=iw-pad*2,dh=ih-pad*2,ox=px+pad,oy=py+pad;if(ia>ba){dw=(ih-pad*2)*ia;ox-=(dw-(iw-pad*2))/2}else{dh=(iw-pad*2)/ia;oy-=(dh-(ih-pad*2))/2}c.filter=t.imageFilter;c.drawImage(img,ox,oy,dw,dh);if(t.halftone){c.filter='none';c.globalAlpha=.18;c.drawImage(getHalftonePatternCanvas(iw-pad*2,ih-pad*2),px+pad,py+pad)}c.restore();}else{c.fillStyle=t.panel;c.fillRect(px+pad,py+pad,iw-pad*2,ih-pad*2);c.fillStyle=t.muted;c.font='bold 14px monospace';c.textAlign='center';c.fillText(a.status==='generating'?'GENERATING':'ASSET PENDING',0,0);}if(f.label){c.fillStyle=t.ink;c.font='700 13px monospace';c.textAlign='left';c.fillText(f.label,px+18,py+ih-18);}if(s.layout==='document'&&i===0)drawArchivalStamp(c,'DECLASSIFIED',px+iw*.68,py+ih*.18,-7,t.accent);if(s.layout==='collage_board'&&i<2)drawMaskingTape(c,px+iw*(i?.7:.25),py+18,120,i?-12:8);c.restore();}
function graphic(c:CanvasRenderingContext2D,g:GraphicElement,time:number,w:number,h:number,t:any){if(time<g.start)return;const m=calculateMotionTransform(g.motion,time,g.start);if(m.opacity<=0)return;const p=g.position||{x:50,y:50},x=p.x/100*w,y=p.y/100*h,col=g.color||t.accent;c.save();c.globalAlpha=m.opacity;if(g.type==='arrow'){const a=g.points?.[0]||[30,70],b=g.points?.[1]||[70,35];drawRedMarkerArrow(c,a[0]/100*w,a[1]/100*h,b[0]/100*w,b[1]/100*h,m.progress,col);}else if(g.type==='red_string'){const a=g.points?.[0]||[25,30],b=g.points?.[1]||[75,60];drawRedString(c,a[0]/100*w,a[1]/100*h,b[0]/100*w,b[1]/100*h,m.progress);}else if(g.type==='stamp')drawArchivalStamp(c,'CONFIDENTIAL',x,y,g.rotation||-8,col);else if(g.type==='tape')drawMaskingTape(c,x,y,(g.scale||1)*150,g.rotation||-12);else if(g.type==='circle'){c.strokeStyle=col;c.lineWidth=5;c.beginPath();c.arc(x,y,(g.scale||1)*70,-Math.PI/2,-Math.PI/2+Math.PI*2*m.progress);c.stroke();}else if(g.type==='underline'){c.strokeStyle=col;c.lineWidth=6;c.beginPath();const l=280*m.progress;c.moveTo(x-l/2,y);c.lineTo(x+l/2,y);c.stroke();}else if(g.type==='pin'){c.fillStyle=col;c.beginPath();c.arc(x,y,10,0,Math.PI*2);c.fill();}else if(g.type==='timeline_line'){c.strokeStyle=col;c.lineWidth=5;c.beginPath();c.moveTo(80,y);c.lineTo(w-80,y);c.stroke();}c.restore();}
function text(c:CanvasRenderingContext2D,e:TextElement,time:number,w:number,h:number,t:any){if(time<e.start)return;const m=calculateMotionTransform(e.motion,time,e.start,e.content.length);if(m.opacity<=0)return;let s=e.content;if(e.motion==='typewriter')s=s.slice(0,m.revealedChars||0);if(!s)return;const x=e.position.x/100*w,y=e.position.y/100*h;c.save();c.globalAlpha=m.opacity;c.translate(x+m.offsetX,y+m.offsetY);c.rotate(((e.rotation||0)+m.rotation)*Math.PI/180);c.scale(m.scale,m.scale);c.fillStyle=e.color||t.ink;c.textAlign='center';c.textBaseline='middle';c.font=e.style==='editorial_serif'?`900 ${e.fontSize}px Georgia`:`900 ${e.fontSize}px sans-serif`;c.fillText(s,0,0);c.restore();}
export function renderShotFrame(c:CanvasRenderingContext2D,s:Shot,time:number,w=1920,h=1080){const theme=getClientVisualTheme(s.visualStyle||'classic_vox',s.styleVariant);bg(c,s,w,h);const visible=(s.assets||[]).filter(a=>time>=a.start);visible.forEach((a,i)=>asset(c,s,a,i,Math.max(1,visible.length),time,w,h,theme));if(s.layout==='hero_archive')drawRedMarkerArrow(c,w*.78,h*.72,w*.62,h*.55,Math.max(0,Math.min(1,(time-.4)/.6)),theme.accent);if(s.layout==='map')drawRedMarkerArrow(c,w*.2,h*.78,w*.48,h*.55,Math.max(0,Math.min(1,(time-.4)/.6)),theme.accent);if(s.layout==='big_number'){c.fillStyle=theme.ink;c.font='900 150px sans-serif';c.textAlign='center';c.fillText('01',w*.3,h*.52);c.strokeStyle=theme.accent;c.lineWidth=8;c.beginPath();c.moveTo(w*.16,h*.66);c.lineTo(w*.44,h*.66);c.stroke();}if(s.layout==='timeline'){c.strokeStyle=theme.accent;c.lineWidth=6;c.beginPath();c.moveTo(w*.08,h*.86);c.lineTo(w*.92,h*.86);c.stroke();}if(s.layout==='collage_board'){drawRedString(c,w*.18,h*.25,w*.5,h*.52,Math.max(0,Math.min(1,(time-.3)/.7)));drawRedString(c,w*.5,h*.52,w*.82,h*.28,Math.max(0,Math.min(1,(time-.6)/.7)));}(s.graphics||[]).forEach(g=>graphic(c,g,time,w,h,theme));(s.text||[]).forEach(e=>text(c,e,time,w,h,theme));c.fillStyle=theme.ink;c.globalAlpha=.7;c.font='11px monospace';c.textAlign='left';c.fillText(`SHOT ${String(s.order).padStart(2,'0')} • ${s.layout.toUpperCase()} • ${s.composition?.assetCount||s.assets.length} ASSETS`,32,h-24);}
