export type LayoutID =
  | 'hero_archive' | 'newspaper' | 'map' | 'photo_stack' | 'document' | 'big_number' | 'timeline' | 'collage_board' | 'split_screen';
export type MotionID =
  | 'paper_drop' | 'paper_slide_left' | 'paper_slide_right' | 'paper_slide_up' | 'paper_slide_down' | 'photo_stack' | 'paper_reveal'
  | 'paper_flip' | 'paper_flip_vertical' | 'photo_flip' | 'card_flip'
  | 'paper_curl' | 'paper_uncurl' | 'paper_tear' | 'tape_peel' | 'photo_swing' | 'photo_rotate' | 'stack_shuffle' | 'stamp_slam' | 'camera_push' | 'camera_pull' | 'jitter'
  | 'typewriter' | 'headline_pop' | 'stamp_in' | 'arrow_draw' | 'string_draw' | 'number_pop' | 'bar_grow' | 'diagram_draw' | 'annotation_reveal' | 'node_connect' | 'panel_slide' | 'slow_reveal' | 'crop_reveal' | 'ticker_slide';
export type VisualDirectionMode = 'auto' | 'manual' | 'hybrid';
export type PhysicalBorderID = 'scissor_cut' | 'clean_edge';
export type PhysicalBackgroundID = 'newsprint' | 'archival' | 'map' | 'corkboard' | 'cream_aged';
export interface PhysicalCollageParams { enabled:boolean; paperLift:number; shadowDepth:number; edgeRoughness:number; tapeStrength:number; depthParallax:number; stopMotion:boolean; frameStep:number; rotationJitter:number; positionJitter:number; settleAmount:number; holdFrames:number; }
export interface ShotComposition { layout:LayoutID; background:PhysicalBackgroundID; border:PhysicalBorderID; primaryMotion:MotionID; autoGenerated?:boolean; assetCount?:number; }
export interface VisualAsset { id:string; type:'image'|'texture'|'stamp'|'tape'|'cutout'; role:'hero'|'secondary'|'background'|'detail'; source:string; assetPrompt?:string; provider?:string; status?:'pending'|'generating'|'ready'|'failed'; position:{x:number;y:number}; scale:number; rotation:number; motion:MotionID; start:number; duration?:number; filter?:'grayscale'|'halftone'|'high_contrast'|'none'; paperCutout?:boolean; shadow?:{enabled:boolean;offset:[number,number];blur:number;opacity:number}; }
export interface TextElement { id:string; content:string; role:'headline'|'date'|'big_number'|'label'|'sublabel'; style:'typewriter'|'condensed_bold'|'editorial_serif'|'stamp'; position:{x:number;y:number}; motion:MotionID; start:number; fontSize:number; color:string; highlightColor?:string; rotation?:number; }
export interface GraphicElement { id:string; type:'arrow'|'circle'|'underline'|'red_string'|'marker'|'stamp'|'tape'|'pin'|'timeline_line'; color:string; motion:MotionID; start:number; points?:[number,number][]; position?:{x:number;y:number}; scale?:number; rotation?:number; }
export interface Shot { shot_id:string; order:number; start:number; end:number; duration:number; narration:string; visual_idea:string; layout:LayoutID; visualStyle?:string; styleVariant?:string; styleReason?:string[]; background:{type:'newsprint'|'archival'|'map'|'corkboard'|'cream_aged';color?:string;textureUrl?:string}; composition?:ShotComposition; physicalCollage?:PhysicalCollageParams; assets:VisualAsset[]; text:TextElement[]; graphics:GraphicElement[]; renderedThumbnail?:string; shotVideoUrl?:string; }
export interface Beat { id:string; shotId:string; start:number; end:number; duration:number; text:string; words:string[]; wordStart:number; wordEnd:number; visualCue:string; }
export interface AudioTimeline { duration:number; fps:number; voiceUrl?:string; beats:Beat[]; generatedAt:string; }
export interface Project { project_id:string; title:string; duration:number; fps:number; resolution:'1920x1080'; style:'vox_paper_collage'; voiceover:boolean; subtitles:boolean; sfx:boolean; shots:Shot[]; script:string; voiceUrl?:string; voiceDuration?:number; audioTimeline?:AudioTimeline; finalVideoUrl?:string; createdAt:string; visualDirectionMode?:VisualDirectionMode; manualVisualStyle?:string; }
export interface PresetLayout { id:LayoutID; name:string; description:string; defaultLayers:string[]; }
export interface PresetMotion { id:MotionID; name:string; category:'paper'|'text'|'graphic'; description:string; }
export interface VisualStyleConfig { name:string; palette:{paper:string;black:string;gray:string;red:string;yellow:string;offWhite:string}; texture:{paper:boolean;grain:boolean;halftone:boolean}; shadows:{enabled:boolean;color:string;defaultBlur:number}; camera:{default:'locked'}; }
export interface QualityGateResult { scriptValid:boolean; voiceValid:boolean; allShotsHaveAssets:boolean; textWithinSafeArea:boolean; timelineContinuous:boolean; ffmpegAvailable:boolean; readyToRender:boolean; messages:string[]; }
